#%RAML 1.0
title: New API
baseUri: https://localhost:8089
description: CRUD operations for crimes databases
mediaType:
  - application/json
protocols:
  - HTTPS
/crimes:
  get:
    displayName: see all crimes in /crimes
    description: Returns all data about crimes
    responses:
      "200":
        description: Array of crime Objects
        body:
          items:
            properties:
              crimes:
                properties:
                  id:
                    example: Example
                    type: string
                  name:
                    example: Example
                    type: string
                  sentenceLength:
                    example: Example
                    type: string
  post:
    displayName: post new crime to /crimes
    body:
      application/json:
        description: Add new crime to database
        properties:
          name:
            example: Example
            type: string
          sentenceLength:
            description: in days
            default: 1
            example: 1
            type: number
            minimum: 1
            maximum: 60
            format: int
          dateSubmitted:
            example: 2022-06-03
            type: date-only
          Active:
            example: true
            type: boolean
    responses:
      "201":
        body:
          properties:
            success:
              example: true
              type: boolean
            crime:
              properties:
                id:
                  description: autogenerated in mule
                  example: Example
                  type: string
                name:
                  example: Example
                  type: string
/crimes/{id}:
  get:
    displayName: /crimes/{id}
    description: Returns data on a specific crime
    queryParameters:
      id:
        default: "11"
        example: Example
        type: string
    body: {}
    responses:
      "200":
        body:
          application/json:
            properties:
              crime:
                description: Returns data from single crime
                properties:
                  id:
                    example: Example
                    type: string
                  name:
                    example: Example
                    type: string
                  sentenceLength:
                    example: 1
                    type: number
                    format: int
    securedBy: []
  post:
    body:
      description: Update content in a crime
      properties:
        id:
          example: Example
          type: string
        name:
          example: Example
          type: string
        sentenceLength:
          example: 1
          type: number
          format: int
    responses:
      "201":
        body:
          properties:
            success:
              example: true
              type: boolean
            crime:
              properties:
                id:
                  example: Example
                  type: string
                name:
                  example: Example
                  type: string
